name: "Update PR Branch on PR Comment"
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  sync:
    
    name: Update PR Branch on PR Comment
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/update'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/akashchi/test-for-sync.git
          git fetch upstream
          
          git remote -v

          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          # git checkout -b feature/x origin/feature/x
          # git merge --no-edit upstream/feature/x
          # git push origin feature/x

          git checkout main
          git merge --no-edit upstream/main
          git push upstream main
