name: "Update PR Branch on PR Comment"
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  sync:
    
    name: Update PR Branch on PR Comment
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/update'
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch PR and target branch names
        id: fetch_pr_and_target_branch
        uses: actions/github-script@v3
        with:
          script: |
            const { issue, repository } = context.payload;
            const [ owner, repo ] = repository.full_name.split('/');
            const { data: pullRequest } = await github.pulls.get({
              owner,
              repo,
              pull_number: issue.number
            });
            const { clone_url: prRemoteUrl } = pullRequest.head.repo;
            console.log(`##[set-output name=pr_remote_url;]${prRemoteUrl}`);
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'WhiteJaeger'
          git config --global user.email 'WhiteJaeger@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream ${{ steps.fetch_pr_and_target_branch.outputs.pr_remote_url }}
          git fetch upstream
          
          git remote -v

          git checkout main
          git merge --no-edit upstream/main
          git push upstream main
      
      - name: Report on update
      - uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Branch was updated!'
            })
