name: "Update PR Branch on PR Comment"
on:
  issue_comment:
    types: [created]
jobs:
  update_pr_branch:
    name: Update PR Branch on PR Comment
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/update'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update PR branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull --unshallow
          
          git remote add upstream https://github.com/WhiteJaeger/test-for-sync.git
          git fetch upstream
          git remote -v
          
          # git checkout pr_remote/${{ steps.fetch_pr_and_target_branch.outputs.pr_branch }}
          # git merge origin/${{ steps.fetch_pr_and_target_branch.outputs.base_branch }} --no-edit --allow-unrelated-histories
          # git push pr_remote main
