name: "Update PR Branch on PR Comment"
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  sync:
    
    name: Update PR Branch on PR Comment
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/update'
    runs-on: ubuntu-latest
    
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: WhiteJaeger
          base: main
          head: main
